vyos_iso_url: "{{ iso }}"
vyos_iso_local: /tmp/vyos.iso
vyos_key_url: http://packages.vyos.net/vyos-release.gpg
vyos_key_local: /tmp/vyos-release.gpg

CD_ROOT: /mnt/cdrom
CD_SQUASH_ROOT: /mnt/cdsquash
SQUASHFS_IMAGE: "{{ CD_ROOT }}/live/filesystem.squashfs"

ROOT_FSTYPE: ext4
ROOT_PARTITION: "{{ volume_drive }}1" # The install partition

WRITE_ROOT: /mnt/wroot
READ_ROOT: /mnt/squashfs
INSTALL_ROOT: /mnt/inst_root

vyos_raw_local: /tmp/vyos_raw_image.img
vyos_qemu_local: /tmp/vyos_qemu_image.qcow2
