#!/usr/bin/env bash

if [ $# -ne 4 ]; then
    echo "Usage: $0 <destination region> <source region> <ami_id> <name>"
    exit 1
fi

set -u
set -e

region=$1
source_region=$2
ami_id=$3
name=$4
    
echo -n "$region: "
new_ami_id=$(aws ec2 copy-image --region $region --source-region $source_region --source-image-id $ami_id --name "$name")
while [ true ]; do
    sleep 15
    set +e
    state=$(aws ec2 describe-images --region $region --image-id $new_ami_id --query 'Images[*].State')
    if [ "$state" = "available" ]; then
        break;
    fi
    echo "$region $new_ami_id: Pending..."
done
set -e
echo "$region $new_ami_id: Making public..."
aws ec2 modify-image-attribute --region $region --image-id $new_ami_id --launch-permission "{\"Add\": [{\"Group\":\"all\"}]}"
while [ true ]; do
    sleep 15
    set +e
    public=$(aws ec2 describe-images --region $region --image-id $new_ami_id --query 'Images[*].Public')
    if [ "$public" = "True" ]; then
        break;
    fi
    echo "$region $new_ami_id: Waiting for public..."
done
set -e
echo "$region $new_ami_id: Done."
