#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <ami name>"
    exit 1
fi

set -u
set -e

name=$1


for region in $(aws ec2 describe-regions --output text --query "Regions[*].RegionName"); do
    echo -n "$region: "
    ami_id=$(aws ec2 describe-images --output text --region $region --owners self --filters "Name=name,Values=$name" --query 'Images[*].ImageId')
    if [ "$ami_id" == "" ]; then
        echo "No AMI by that name."
        continue
    fi
    echo "Deleting AMI: $ami_id ($name)"
    set +e
    aws ec2 deregister-image --region $region --image-id $ami_id
    set -e
done

while [ true ]; do
    still_waiting=0
    for region in $(aws ec2 describe-regions --output text --query "Regions[*].RegionName"); do
        echo -n "Checking for AMI still lingering around in $region: "
        ami_id=$(aws ec2 describe-images --output text --region $region --owners self --filters "Name=name,Values=$name" --query 'Images[*].ImageId')
        if [ "$ami_id" == "" ]; then
            echo "Gone."
        else
            echo "Still waiting."
            still_waiting=1
        fi
    done
    if [ $still_waiting -eq 0 ]; then
        break;
    fi
    sleep 30
done
