---
# tasks file for ec2-cleanup
- name: Grab instance IDs
  ec2_instance_info:
    filters:
      instance-state-name:  [ "shutting-down", "stopping", "stopped","running" ] 
      "tag:Name": "vyos-build-ami"
      "tag:Type": "VyOS"
    region: "{{ ec2_region }}"
  register: ec2_instances

- name: Delete the EC2 Instance
  ec2:
    state: absent
    region: "{{ ec2_region }}"
    instance_ids: "{{ item.instance_id }}"
    wait: True
  ignore_errors: True
  with_items: "{{ ec2_instances.instances }}"

- name: Delete key pair
  ec2_key:
    name: "{{ key_pair_name }}"
    state: absent
    region: "{{ ec2_region }}"
  ignore_errors: True

- name: Delete security group
  ec2_group:
    state: absent
    group_id: "{{ security_group.group_id }}"
    region: "{{ ec2_region }}"

- name: Remove key file from {{ temp_folder }}
  file:
    path: "{{ temp_folder }}"
    state: absent
